(function(k){var h,e,m,j="https://github.com/api/v2/json/",d=function(a,c,l){for(var i=+new Date,d=document.createElement("script");void 0!==b.__jsonp_callbacks[i];)i+=Math.random();b.__jsonp_callbacks[i]=function(){delete b.__jsonp_callbacks[i];c.apply(l,arguments)};var f="?";0<=a.indexOf("?")&&(f="&");a+=f+"callback="+encodeURIComponent("gh.__jsonp_callbacks["+i+"]");h&&e&&(a+="&login="+h+"&token="+e);m&&(a+="&access_token="+m);d.setAttribute("src",j+a);document.getElementsByTagName("head")[0].appendChild(d)},
g=function(a,c){var b=document.createElement("form"),d=document.createElement("iframe");document.body.appendChild(d);var f=void 0!==d.contentDocument?d.contentDocument:d.contentWindow.document,g,e,c=c||{};b.setAttribute("method","post");b.setAttribute("action",j+a);for(g in c)if(c.hasOwnProperty(g))e=document.createElement("input"),e.type="hidden",e.value=encodeURIComponent(c[g]),b.appendChild(e);d.setAttribute("style","display: none;");f.body.appendChild(b);b.submit()},f=function(a){if((!h||!e||
h!==a)&&!m)throw new TypeError("gh: Must be authenticated to do that.");},n=function(a,c){return function(){var b=j;j=a;c.apply(this,arguments);j=b}},b=k.gh={};b.__jsonp_callbacks={};b.authenticate=function(a,c,b){h=a;e=c;m=b;return this};b.user=function(a){if(!(this instanceof b.user))return new b.user(a);this.username=a};b.user.prototype.show=function(a,c){d("user/show/"+this.username,a,c);return this};b.user.prototype.update=function(a){f(this.username);var c,b={login:h,token:e};for(c in a)a.hasOwnProperty(c)&&
(b["values["+c+"]"]=encodeURIComponent(a[c]));g("user/show/"+this.username,b);return this};b.user.prototype.following=function(a,c){d("user/show/"+this.username+"/following",a,c)};b.user.prototype.followers=function(a,c){d("user/show/"+this.username+"/followers",a,c)};b.user.prototype.follow=function(a){f.call(this);g("user/follow/"+a);return this};b.user.prototype.unfollow=function(a){f.call(this);g("user/unfollow/"+a);return this};b.user.prototype.watching=function(a,c){d("repos/watched/"+this.username,
a,c);return this};b.user.prototype.orgs=function(a,c){d("user/show/"+this.username+"/organizations",a,c);return this};b.user.prototype.allOrgRepos=function(a){f(this.username);d("organizations/repositories",a);return this};b.user.prototype.repos=function(a,c,l){b.repo.forUser(this.username,a,c,l);return this};b.user.prototype.allRepos=function(a,c){function l(g){0==g.repositories.length?a.call(c,{repositories:d}):(d=d.concat(g.repositories),e+=1,b.repo.forUser(f,l,c,e))}var d=[],f=this.username,e=
1;b.repo.forUser(f,l,c,e);return this};b.user.prototype.forkRepo=function(a,c){f(this.username);g("repos/fork/"+a+"/"+c);return this};b.user.prototype.pushable=function(a,c){f(h);d("repos/pushable",a,c)};b.user.prototype.publicGists=n("http://gist.github.com/api/v1/json/gists/",function(a,c){d(this.username,a,c);return this});b.user.search=function(a,c,b){d("user/search/"+a,c,b);return this};b.repo=function(a,c){if(!(this instanceof b.repo))return new b.repo(a,c);this.repo=c;this.user=a};b.repo.prototype.show=
function(a,c){d("repos/show/"+this.user+"/"+this.repo,a,c);return this};b.repo.prototype.update=function(a){f(this.user);var c,b={login:h,token:e};for(c in a)a.hasOwnProperty(c)&&(b["values["+c+"]"]=encodeURIComponent(a[c]));g("repos/show/"+this.user+"/"+this.repo,b);return this};b.repo.prototype.tags=function(a,c){d("repos/show/"+this.user+"/"+this.repo+"/tags",a,c);return this};b.repo.prototype.branches=function(a,c){d("repos/show/"+this.user+"/"+this.repo+"/branches",a,c);return this};b.repo.prototype.languages=
function(a,c){d("/repos/show/"+this.user+"/"+this.repo+"/languages",a,c);return this};b.repo.prototype.network=function(a,c){d("repos/show/"+this.user+"/"+this.repo+"/network",a,c);return this};b.repo.prototype.contributors=function(a,c,b){var i="repos/show/"+this.user+"/"+this.repo+"/contributors";b&&(i+="/anon");d(i,a,c);return this};b.repo.prototype.collaborators=function(a,c){d("repos/show/"+this.user+"/"+this.repo+"/collaborators",a,c);return this};b.repo.prototype.addCollaborator=function(a){f(this.user);
g("repos/collaborators/"+this.repo+"/add/"+a);return this};b.repo.prototype.removeCollaborator=function(a){f(this.user);g("repos/collaborators/"+this.repo+"/remove/"+a);return this};b.repo.prototype.setPrivate=function(){f(this.user);g("repo/set/private/"+this.repo);return this};b.repo.prototype.setPublic=function(){f(this.user);g("repo/set/public/"+this.repo);return this};b.repo.search=function(a,c,b,i){a="repos/search/"+a.replace(" ","+");"function"===typeof c&&(i=b=c={});var e,f="";for(e in c)c.hasOwnProperty(e)&&
(f+=e+"="+c[e]+"&");e=f.replace(/&$/,"");d(a+("?"+e),b,i);return this};b.repo.forUser=function(a,c,b,e){e||(e=1);d("repos/show/"+a+"?page="+e,c,b);return this};b.repo.create=function(a,c){f(h);c.name=a;g("repos/create",c);return this};b.repo.del=function(a){f(h);g("repos/delete/"+a);return this};b.commit=function(a,c,d){if(!(this instanceof b.commit))return new b.commit(a,c,d);this.user=a;this.repo=c;this.sha=d};b.commit.prototype.show=function(a,c){d("commits/show/"+this.user+"/"+this.repo+"/"+this.sha,
a,c);return this};b.commit.forBranch=function(a,c,b,e,f){d("commits/list/"+a+"/"+c+"/"+b,e,f);return this};b.commit.forPath=function(a,c,b,e,f,g){d("commits/list/"+a+"/"+c+"/"+b+"/"+e,f,g);return this};b.issue=function(a,c,d){if(!(this instanceof b.issue))return new b.commit(a,c,d);this.user=a;this.repo=c;this.number=d};b.issue.prototype.show=function(a,c){d("issues/show/"+this.user+"/"+this.repo+"/"+this.number,a,c);return this};b.issue.prototype.comments=function(a,c){d("issues/comments/"+this.user+
"/"+this.repo+"/"+this.number,a,c);return this};b.issue.prototype.close=function(){f(this.user);g("issues/close/"+this.user+"/"+this.repo+"/"+this.number);return this};b.issue.prototype.reopen=function(){f(this.user);g("issues/reopen/"+this.user+"/"+this.repo+"/"+this.number);return this};b.issue.prototype.update=function(a,c){f(this.user);g("issues/edit/"+this.user+"/"+this.repo+"/"+this.number,{title:a,body:c});return this};b.issue.prototype.addLabel=function(a){g("issues/label/add/"+this.user+
"/"+this.repo+"/"+a+"/"+this.number);return this};b.issue.prototype.removeLabel=function(a){g("issues/label/remove/"+this.user+"/"+this.repo+"/"+a+"/"+this.number);return this};b.issue.prototype.comment=function(a){f(h);g("/issues/comment/"+user+"/"+repo+"/"+this.number,{comment:a});return this};b.issue.labels=function(a,c){d("issues/labels/"+a+"/"+c,callback,context);return this};b.issue.open=function(a,c,b){f(h);g("issues/open/"+h+"/"+a,{title:c,body:b});return this};b.issue.search=function(a,c,
b,e,f,g){d("/issues/search/"+a+"/"+c+"/"+b+"/"+e,f,g);return this};b.issue.list=function(a,c,b,e,f){d("issues/list/"+a+"/"+c+"/"+b,e,f);return this};b.gist=function(a){if(!(this instanceof b.gist))return new b.gist(a);this.id=a};b.gist.prototype.show=n("http://gist.github.com/api/v1/json/",function(a){d(this.id,a,cont);return this});b.gist.prototype.file=n("http://gist.github.com/raw/v1/json/",function(a,c){d(this.id+"/"+a,c,cont);return this});b.object=function(a,c){if(!(this instanceof b.object))return new b.object(a,
c);this.user=a;this.repo=c};b.object.prototype.tree=function(a,c,b){d("tree/show/"+this.user+"/"+this.repo+"/"+a,c,b);return this};b.object.prototype.blob=function(a,c,b,e){d("blob/show/"+this.user+"/"+this.repo+"/"+c+"/"+a,b,e);return this};b.object.prototype.blobMeta=function(a,b,e,f){d("blob/show/"+this.user+"/"+this.repo+"/"+b+"/"+a+"?meta=1",e,f);return this};b.object.prototype.blobAll=function(a,b,e){d("blob/all/"+this.user+"/"+this.repo+"/"+a,b,e);return this};b.object.prototype.blobFull=function(a,
b,e){d("blob/full/"+this.user+"/"+this.repo+"/"+a,b,e);return this};b.network=function(a,c){if(!(this instanceof b.network))return new b.network(a,c);this.user=a;this.repo=c};b.network.prototype.data=n("http://github.com/",function(a,b,e,f,g){d(this.user+"/"+this.repo+"/network_data_chunk?"+a+"&"+b+"&"+e,f,g);return this});b.network.prototype.meta=n("http://github.com/",function(a,b){d(this.user+"/"+this.repo+"/network_meta",a,b);return this});b.pulls=function(a,c){if(!(this instanceof b.pulls))return new b.pulls(a,
c);this.user=a;this.repo=c};b.pulls.prototype.allPulls=function(a,b){d("pulls/"+this.user+"/"+this.repo,a,b);return this};b.pulls.prototype.forState=function(a,b,e){d("pulls/"+this.user+"/"+this.repo+"/"+a,b,e);return this};b.pulls.prototype.forNumber=function(a,b,e){d("pulls/"+this.user+"/"+this.repo+"/"+a,b,e);return this}})(window);if(!String.prototype.format)String.prototype.format=function(){var k=this;for(arg in arguments)k=k.replace(RegExp("\\{"+arg+"\\}","g"),arguments[arg]);return k};
(function(k){var h=function(e){var e=e.message,h=e.indexOf("\n");if(0>h||0===h)h=80;return e=e.substr(0,Math.min(80,e.length,h))};(k.jscommits={}).showCommits=function(e,m,j){var d=document.createElement("div"),g=document.createElement("div");d.className="jscommits-heading";j.className+=" jscommits-panel";d.innerHTML="Latest commits for <a href='https://www.github.com/{0}/{1}'>{1}</a> repository.".format(e,m);j.appendChild(d);j.appendChild(g);gh.commit.forBranch(e,m,"master",function(d){for(var j=
5<d.commits.length?5:d.commits.length,b=!1,a=0;a<j;a++){var c=d.commits[a],l=document.createElement("div"),i=document.createElement("span"),k=document.createElement("span");l.className=b?"jscommits-commit flip-color":"jscommits-commit";i.className="jscommits-message";k.className="jscommits-author";i.innerHTML="<a href='https://www.github.com/{0}/{1}/commit/{2}'>{3}</a>".format(e,m,c.id,h(c));k.innerHTML="<a href='https://www.github.com/{0}'>{1}</a>".format(e,e.substr(0,Math.min(20,e.length)));l.appendChild(k);
l.appendChild(i);g.appendChild(l);b=!b}})}})(window);
